### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by Sreeram095** [ios-mcn/worklows-permissions#11]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| RAN | https://github.com/ios-mcn-ran-distributed/openairinterface5g https://github.com/ios-mcn-ran-distributed/o1-adapter | IISc | Sreeram M | Sreeram095 | Read | xxx |

**Comment by vinaykz** [comment]
Approved..

**Comment by joseajeesh** [comment]
ok
