### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by Rony-1999** [ios-mcn/worklows-permissions#12]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| RAN |  https://github.com/ios-mcn-ran-distributed/openairinterface5g  https://github.com/ios-mcn-ran-distributed/o1-adapter | CazeLabs/IISc | RONAK KANTHALIYA | Rony-1999 | Read| xxx |

**Comment by joseajeesh** [comment]
done

**Comment by Rony-1999** [comment]
Hi Ajeesh,

The o1-adapter available in IOS-MCN git is old please rebase it to the
latest version.

https://gitlab.eurecom.fr/oai/o1-adapter

Regards and Thanks,
Ronak Kanthaliya
