### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by Ramuediga** [ios-mcn/worklows-permissions#13]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| RAN | [openairinterface5g](https://github.com/ios-mcn-ran-distributed/openairinterface5g) <br />[o1-adapter](https://github.com/ios-mcn-ran-distributed/o1-adapter) | IISc | Ramagiddaiah E | Ramuediga | Read/Write | xxx |

**Comment by vinaykz** [comment]
Approved - @Ajeesh-Jose : please provide the access.

**Comment by joseajeesh** [comment]
ok
