### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by kiran09kadam** [ios-mcn/worklows-permissions#17]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| CORE | Repo URL | IISc | Kiran Kadam | kiran09kadam | Read | To update the bug resolution status |

1. Please give the requested informtion completely 
2. Respctive subproject leder is the approver for the read and write acccess. If the issue is raised by the respective subproject leader then no further approval is required
3. Maintiner or above level access shall be approved by TOC-PMC  (use @skdwriting @ushapadminic )

-->

**Comment by ak2btvm** [comment]
Approved

**Comment by joseajeesh** [comment]
done
