### ISSUE TITLE
Access Request to IOS-MCN CORE

### ISSUE THREAD

**Issue by avreddy453** [ios-mcn/worklows-permissions#18]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| CORE | https://github.com/ios-mcn-core/ios-mcn-core | IISc | Venkatareddy | avreddy453 | Read |  |

**Comment by vinaykz** [comment]
LGTM

**Comment by vinaykz** [comment]
Approved

**Comment by Venkatareddy-iosmcn** [comment]
Still, I do not see ios-mcn core on my GitHub page. I checked my inbox but did not see any email also. Can you check, please. thank you.

**Comment by ak2btvm** [comment]
Approved

**Comment by avreddy453** [comment]
@joseajeesh, Still I do not see in my github page. I am seeing only .github. Please give me access to ios-mcn-core.

**Comment by joseajeesh** [comment]
done. Access invite send

**Comment by Venkatareddy-iosmcn** [comment]
@joseajeesh I did not receive any email related to this. I checked spam too.

**Comment by Venkatareddy-iosmcn** [comment]
Hi @joseajeesh, I do not have access permission to iosmcn-core yet. This is slowing down my work. Please help resolve this issue at the earliest. Thank  you.
