### ISSUE TITLE
Access to IOS-MCN RAN Distributed

### ISSUE THREAD

**Issue by avreddy453** [ios-mcn/worklows-permissions#19]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| RAN-DISTRIBUTED | https://github.com/ios-mcn-ran-distributed/openairinterface5g | IISc | Venkatareddy | avreddy453 | Read/Write | This is my personal email |

**Comment by joseajeesh** [comment]
Send the access invite
