### ISSUE TITLE
Access Request to IOS MCN core

### ISSUE THREAD

**Issue by svranand** [ios-mcn/worklows-permissions#20]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| CORE | https://github.com/ios-mcn-core | IISc | Anand SVR | svranand | Read | xxx |

**Comment by vinaykz** [comment]
LGTM

**Comment by joseajeesh** [comment]
done
