### ISSUE TITLE
Access Request IOS MCN RAN distributed

### ISSUE THREAD

**Issue by svranand** [ios-mcn/worklows-permissions#21]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Memeber Name | GITHUB USER ID |Access Level | Remarks |
|--|--|--|--|--|--|--|
| RAN | https://github.com/ios-mcn-ran-distributed | IISc | Anand SVR | svranand | Read | xxx |

**Comment by vinaykz** [comment]
LGTM

**Comment by joseajeesh** [comment]
Send the access invite to the user
