### ISSUE TITLE
Access Request

### ISSUE THREAD

**Issue by ak2btvm** [ios-mcn/worklows-permissions#30]
**Access Request Reason/Description:**

| Project | Repo URL | Organization |Team Member Name | GITHUB USER ID | Access Level | Remarks |
|--|--|--|--|--|--|--|
| SMO | https://github.com/ios-mcn-smo | C-DAC | Aneesh Kumar K B | ak2btvm | Read | xxx |

**Comment by sknrao** [comment]
Approved.

**Comment by joseajeesh** [comment]
done , access invite sent
